services:

  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db_volume:/var/lib/postgresql/data/
    env_file:
      - ../.env

  wb_service:
    container_name: wb_service
    build: ..
    restart: always
    env_file:
      - ../.env
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  db_volume:
