services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db_volume:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=password


volumes:
  db_volume:
