name: pre-commit

on:
 pull_request:
  types: [opened, synchronize, reopened]

jobs:
 linters:
  name: Run linters
  runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install

    - name: flake8
      run:  |
          poetry run isort src/

    - name: flake8
      run:  |
        poetry run flake8 src/

    - name: mypy
      run:  |
        poetry run mypy src/

 tests:
  name: Run tests
  runs-on: ubuntu-latest
  needs: linters
  services:
    docker:
      image: docker
      options: --privileged
  steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Compose
      run: |
        cd infra/
        echo "POSTGRES_PASSWORD=password" >> .env
        docker compose -f docker-compose-test.yaml up -d --build
    - name: Run Pytest
      run: |
        sleep 3
        cd infra/
        docker compose -f docker-compose-test.yaml exec wb_service pytest --cov --cov-fail-under=90 --cov-report term-missing
    - name: Tear down Docker Compose
      if: always()
      run: docker compose -f docker-compose-test.yaml down
